export const universities = [
  ("Adama Science and Technology University",
  "Adama Science and Technology University"),
  ("Addis Ababa Science and Technology University",
  "Addis Ababa Science and Technology University"),
  ("Addis Ababa University", "Addis Ababa University"),
  ("Adigrat University", "Adigrat University"),
  ("Ambo University", "Ambo University"),
  ("Arba Minch University", "Arba Minch University"),
  ("Arsi Unuversuty", "Arsi Unuversuty"),
  ("Assosa University", "Assosa University"),
  ("Axum University", "Axum University"),
  ("Bahir Dar University", "Bahir Dar University"),
  ("Bonga University", "Bonga University"),
  ("Borana University", "Borana University"),
  ("Bule Hora University", "Bule Hora University"),
  ("Dambi Dollo University", "Dambi Dollo University"),
  ("Debark University", "Debark University"),
  ("Debre Berhan University", "Debre Berhan University"),
  ("Debre Markos Universityy", "Debre Markos Universityy"),
  ("Debre Tabor University", "Debre Tabor University"),
  ("Defence University", "Defence University"),
  ("Dilla University", "Dilla University"),
  ("Dire Dawa University", "Dire Dawa University"),
  ("Ethiopian Civil Service University", "Ethiopian Civil Service University"),
  ("Ethiopian Police University College",
  "Ethiopian Police University College"),
  ("Gambella University", "Gambella University"),
  ("Haramaya University", "Haramaya University"),
  ("Hawassa University", "Hawassa University"),
  ("Injibara University", "Injibara University"),
  ("Jijiga University", "Jijiga University"),
  ("Jimma University", "Jimma University"),
  ("Jinka University", "Jinka University"),
  ("Kebri Dehar University", "Kebri Dehar University"),
  ("Kotebe Metropolitan University", "Kotebe Metropolitan University"),
  ("Meda Walabu University", "Meda Walabu University"),
  ("Mekdela Amba University", "Mekdela Amba University"),
  ("Mekelle University", "Mekelle University"),
  ("Mettu University", "Mettu University"),
  ("Mizan Tepi University", "Mizan Tepi University"),
  ("Oda Bultum University", "Oda Bultum University"),
  ("Oromia State University", "Oromia State University"),
  ("Raya University", "Raya University"),
  ("Salale University", "Salale University"),
  ("Semera University", "Semera University"),
  ("University of Gondar", "University of Gondar"),
  ("Wachamo University", "Wachamo University"),
  ("Werabe University", "Werabe University"),
  ("Wolaita Sodo University", "Wolaita Sodo University"),
  ("Woldia University", "Woldia University"),
  ("Wolkite University", "Wolkite University"),
  ("Wollega University", "Wollega University"),
  ("Wollo University", "Wollo University"),
];
